# To customize values for a specific cluster, create a separate values file and point to it in the config file:
# argocd/cluster-addons/cluster-config/<cluster>/config.json

# Default values for cluster-addons.
# You can override these values for each addon below.
default:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # Create namespace if it does not exist.
    automated: # Automated sync options.
      prune: false # Delete resources that are not in git (e.g. deleted files).
      selfHeal: true # Reconcile resources that are not in desired state (e.g. due to manual edits).
      allowEmpty: true # Allow empty manifests to be applied. This is useful for Helm charts that may not have any manifests.
ingressNginxAddon:
  enabled: true
  chartVersion: 4.11.2
  valuesObject:
    fullnameOverride: ingress-nginx
reloaderAddon:
  enabled: true
  chartVersion: 1.1.0
  valuesObject: {}
certManagerAddon:
  enabled: true
  chartVersion: 1.15.3
  # Values to be passed to the main cert-manager chart.
  # For a full list of values, see: https://artifacthub.io/packages/helm/cert-manager/cert-manager
  certManagerValues: {}
  # Values to be passed to the custom cert-manager-crds chart.
  certManagerCRDsValues:
    crdsVersion: 1.15.3
    email: "nadav@koalaops.com"
